# tinty configuration for dotfiles integration

# Data directories (templates and schemes)
[data]
base16 = "~/.local/share/tinty/base16-schemes"
base24 = "~/.local/share/tinty/base24-schemes"

# Templates directories
[templates]
base16 = "~/.local/share/tinty/base16-alacritty/templates"

# Application integrations
[[items]]
path = "~/.config/alacritty/alacritty.toml"
name = "alacritty"
template = "base16"
supported_systems = ["base16", "base24"]

[[items]]
path = "~/.config/tmux/tmux.conf"
name = "tmux"
supported_systems = ["base16"]

# Default themes
[themes]
default-dark = "base16-mocha"
default-light = "base16-latte"

# Shell integration
[shell]
enable = true
flavor = "zsh"
